// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServidorApi.Data;

#nullable disable

namespace ServidorApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260530021023_AddCamposBloqueio")]
    partial class AddCamposBloqueio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ServidorApi.Models.Categoria", b =>
                {
                    b.Property<int>("IDCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDCategoria"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)")
                        .HasColumnName("tipo_categoria");

                    b.Property<string>("categoria")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nome_categoria");

                    b.HasKey("IDCategoria");

                    b.ToTable("tb_categoria");
                });

            modelBuilder.Entity("ServidorApi.Models.Conta", b =>
                {
                    b.Property<int>("IDConta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_conta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDConta"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativa_conta");

                    b.Property<string>("NomeConta")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nome_conta");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("IDConta");

                    b.HasIndex("UsuarioID");

                    b.ToTable("tb_conta");
                });

            modelBuilder.Entity("ServidorApi.Models.Entradas", b =>
                {
                    b.Property<int>("IDEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_entrada");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDEntrada"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_entrada");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descricao_entrada");

                    b.Property<int>("IDCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<int>("IDConta")
                        .HasColumnType("int")
                        .HasColumnName("id_conta");

                    b.Property<decimal>("ValorEntrada")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_entrada");

                    b.HasKey("IDEntrada");

                    b.HasIndex("IDCategoria");

                    b.HasIndex("IDConta");

                    b.ToTable("tb_entrada", (string)null);
                });

            modelBuilder.Entity("ServidorApi.Models.Saida", b =>
                {
                    b.Property<int>("IDSaida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_saida");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDSaida"));

                    b.Property<DateTime>("DataSaida")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_saida");

                    b.Property<int>("IDCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<int>("IDConta")
                        .HasColumnType("int")
                        .HasColumnName("id_conta");

                    b.Property<decimal>("ValorSaida")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_saida");

                    b.HasKey("IDSaida");

                    b.HasIndex("IDCategoria");

                    b.HasIndex("IDConta");

                    b.ToTable("tb_saida");
                });

            modelBuilder.Entity("ServidorApi.Models.Saldo_Conta", b =>
                {
                    b.Property<int>("IDConta")
                        .HasColumnType("int")
                        .HasColumnName("id_conta");

                    b.Property<decimal>("SaldoAtual")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("saldo_atual_conta");

                    b.Property<decimal>("TotalEntrada")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_entrada_conta");

                    b.Property<decimal>("TotalSaida")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_saida_conta");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ultima_atualizacao_conta");

                    b.HasKey("IDConta");

                    b.ToTable("tb_saldo_conta");
                });

            modelBuilder.Entity("ServidorApi.Models.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("dataCriacao_usuario");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("eMail_usuario");

                    b.Property<int>("Idade")
                        .HasColumnType("int")
                        .HasColumnName("idade_usuario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome_usuario");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("senha_usuario");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sobreNome_usuario");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefone_usuario");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("tipo_usuario");

                    b.HasKey("ID");

                    b.ToTable("tb_usuario");
                });

            modelBuilder.Entity("ServidorApi.Models.Conta", b =>
                {
                    b.HasOne("ServidorApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ServidorApi.Models.Entradas", b =>
                {
                    b.HasOne("ServidorApi.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IDCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServidorApi.Models.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("IDConta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("ServidorApi.Models.Saida", b =>
                {
                    b.HasOne("ServidorApi.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IDCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServidorApi.Models.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("IDConta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("ServidorApi.Models.Saldo_Conta", b =>
                {
                    b.HasOne("ServidorApi.Models.Conta", "Conta")
                        .WithMany()
                        .HasForeignKey("IDConta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conta");
                });
#pragma warning restore 612, 618
        }
    }
}
