// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServidorApi.Data;

#nullable disable

namespace ServidorApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260625010804_AdicionarIDUsuarioEConverterTipoCategoria")]
    partial class AdicionarIDUsuarioEConverterTipoCategoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ServidorApi.Models.Categoria", b =>
                {
                    b.Property<int>("IDCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDCategoria"));

                    b.Property<int?>("IDUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("tipo_categoria");

                    b.Property<string>("categoria")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nome_categoria");

                    b.HasKey("IDCategoria");

                    b.ToTable("tb_categoria");
                });

            modelBuilder.Entity("ServidorApi.Models.Conta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_conta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ativo_conta");

                    b.Property<DateTime?>("BloqueadoAte")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("bloqueado_ate");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao_conta");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("email_conta");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("senha_conta");

                    b.Property<int>("TentativasLogin")
                        .HasColumnType("int")
                        .HasColumnName("tentativas_login");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("tipo_conta");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("ID");

                    b.HasIndex("UsuarioID")
                        .IsUnique();

                    b.ToTable("tb_conta");
                });

            modelBuilder.Entity("ServidorApi.Models.Entradas", b =>
                {
                    b.Property<int>("IDEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_entrada");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDEntrada"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_entrada");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descricao_entrada");

                    b.Property<int>("IDCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("ValorEntrada")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_entrada");

                    b.HasKey("IDEntrada");

                    b.HasIndex("IDCategoria");

                    b.HasIndex("IDUsuario");

                    b.ToTable("tb_entrada", (string)null);
                });

            modelBuilder.Entity("ServidorApi.Models.Meta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_meta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_inicio_meta");

                    b.Property<DateTime?>("DataLimite")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_limite_meta");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("descricao_meta");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome_meta");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status_meta");

                    b.Property<decimal>("ValorAlvo")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_alvo_meta");

                    b.Property<decimal>("ValorAtual")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_atual_meta");

                    b.HasKey("ID");

                    b.HasIndex("IDUsuario");

                    b.ToTable("tb_meta");
                });

            modelBuilder.Entity("ServidorApi.Models.Saida", b =>
                {
                    b.Property<int>("IDSaida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_saida");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IDSaida"));

                    b.Property<DateTime>("DataSaida")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_saida");

                    b.Property<int>("IDCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<int>("IDUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("ValorSaida")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("valor_saida");

                    b.HasKey("IDSaida");

                    b.HasIndex("IDCategoria");

                    b.HasIndex("IDUsuario");

                    b.ToTable("tb_saida");
                });

            modelBuilder.Entity("ServidorApi.Models.Usuario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Idade")
                        .HasColumnType("int")
                        .HasColumnName("idade_usuario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nome_usuario");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sobreNome_usuario");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefone_usuario");

                    b.HasKey("ID");

                    b.ToTable("tb_usuario");
                });

            modelBuilder.Entity("ServidorApi.Models.Conta", b =>
                {
                    b.HasOne("ServidorApi.Models.Usuario", "Usuario")
                        .WithOne("Conta")
                        .HasForeignKey("ServidorApi.Models.Conta", "UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ServidorApi.Models.Entradas", b =>
                {
                    b.HasOne("ServidorApi.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IDCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServidorApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ServidorApi.Models.Meta", b =>
                {
                    b.HasOne("ServidorApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ServidorApi.Models.Saida", b =>
                {
                    b.HasOne("ServidorApi.Models.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("IDCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServidorApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IDUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ServidorApi.Models.Usuario", b =>
                {
                    b.Navigation("Conta");
                });
#pragma warning restore 612, 618
        }
    }
}
